
# tap "homebrew/cask-fonts"


# Mac App Store command-line interface
brew "mas"
brew "starship"

cask "wezterm"
cask "google-chrome"
cask 'visual-studio-code'

cask "maczip"

# Source Code Pro
# cask "font-sourcecodepro-nerd-font-mono"
# 微软 Cascadia Code
cask "font-caskaydia-cove-nerd-font"
# 播放器
cask "iina"
# 鼠标增强
cask "mos"

mas "WeChat", id: 836500024