tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Shell extension to jump to frequently used directories
brew "autojump"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Mac App Store command-line interface
brew "mas"

cask "iterm2"
cask "google-chrome"
cask 'visual-studio-code'
cask "sogouinput"
# 屏保
cask "aerial"
cask "maczip"

# Source Code Pro
# cask "font-sourcecodepro-nerd-font-mono"
# 微软 Cascadia Code
cask "font-caskaydia-cove-nerd-font"
# 播放器
cask "iina"
# 鼠标增强
cask "mos"

mas "WeChat", id: 836500024